#!/usr/bin/bash
#Build the four standard configurations

ROOT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $ROOT_DIR/console/pico
make clean
make
cd $ROOT_DIR/console/pico_w
make clean
make
cd $ROOT_DIR/bin/pico
make clean
make
cd $ROOT_DIR/bin/pico_w
make clean
make
cd $ROOT_DIR
find . -name "bbcbasic_*.uf2" -ls
