# Build defaults: Override by options on the make command
BOARD=pico_w
CYW43=GPIO
STDIO=USB+UART
LFS=Y
FAT=N
SOUND=SDL
SERIAL_DEV=1
MIN_STACK=Y
SUFFIX=_pkc

# BASIC examples selection
DEVICE = -d all -d pico
BUILD = -b all -b console

include ../../src/pico/Makefile
