#!/bin/bash
# Create an alphabetical symbol table in sympico.i for inclusion in
# sympico.c as called by sysadr in bbccon.c.  To add more symbols
# to the table place them anywhere in symbols.txt.  Then add
# the relevant include files to sympico.c

{
    for i in "$@"
    do
        cat $i
    done
} | sort | {
	printf "// sympico.i -- Alphabetical list of SDK function calls\n"
	printf "// Automatically generated by sympico.sh -- DO NOT EDIT\n"
	first=true
	while read i
	do
case $first in
false)
		printf ",\n"
esac
		first=false
		printf "SYMADD(%s)" "$i"
	done
	printf "\n"
} > sympico.i
