# Build defaults: Override by options on the make command
BOARD=pico+w
CYW43=BACKGROUND
NET_HEAP=1
STDIO=USB+UART
LFS=Y
FAT=N
SOUND=SDL
SERIAL_DEV=1
MIN_STACK=Y
SUFFIX=_pwc

# BASIC examples selection
DEVICE = -d all -d pico_w
BUILD = -b all -b console

include ../../src/pico/Makefile
