# Build defaults: Override by options on the make command
BOARD=pico_w
CYW43=BACKGROUND
STDIO=USB+UART
LFS=Y
FAT=N
SOUND=SDL
SERIAL_DEV=1
MIN_STACK=Y
SUFFIX=_pwc

# Select files loaded into LFS
LFS_FILES=../../console/pico_w/examples/* ../../console/pico_w/examples/lib/*
LFS_EXTRA=../../console/pico_w/examples

include ../../src/pico/Makefile
