# Build defaults: Override by options on the make command
BOARD=vgaboard_sd_w
CYW43=GPIO
STDIO=USB
GRAPH=Y
LFS=Y
FAT=N
SOUND=N
SERIAL_DEV=0
PRINTER=N
MIN_STACK=Y
SUFFIX=_pkv

# BASIC examples selection
DEVICE = -d all -d pico
BUILD = -b all -b gui

include ../../src/pico/Makefile
